#!/usr/bin/env bash

STAT=`playerctl status 2>/dev/null`
if [[ $STAT == "" ]]; then
    printf "\n"
elif [[ $(playerctl status 2>/dev/null) == "Playing" ]]; then
    printf "Playing: $(playerctl metadata title)\n"
else
    printf "Paused: $(playerctl metadata title)\n"
fi
